### PR TITLE
upgrade rusqlite due to rust-lang/rust#49799 

### PR DESCRIPTION
**Pull request by hdhoang**
I have some trouble building this crate without windows. Please exercise this PR on your side, sorry

### CODE REVIEW

**Comment by chyyran** [comment]
There are some breaking changes to rusqlite since 0.13.0, particularly with i32 being replaced by usize in parameterized queries. Could you ensure that everything builds as expected?

**Comment by hdhoang** [comment]
I'll try building it on a CI service or so.

**Comment by hdhoang** [comment]
I did a pretty botched job, and didn't even bump rusqlite in the support crates. I have more WIP in this branch, built by travis https://github.com/hdhoang/seiri/tree/ci

So far I have found `&[] ` needs to be replaced with `rusqlite::NO_PARAMS`. More troublesome is somehow all columns in `add_track` want String.

**Comment by chyyran** [comment]
I've reverted the PR for now since I don't have much time lately to test this, if you manage to update everything to work with rusqlite 0.15.0, I'll merge those changes in then.

**Comment by chyyran** [comment]
#11 fixes this issue. rusqlite is now at 0.15.0

**Pull request merged**
